[build-system]
requires = ["setuptools", "numpy<2"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["interval"]

[project]
name = "npinterval"  # as it would appear on PyPI
version = "0.0.1"
dependencies = [
    "numpy<2"
]


